Meteo/urls.py
from django.urls import path
from . import views

app_name = 'Meteo'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('registo/', views.registo_view, name='registo'),
    path('', views.home, name='home'),
    path('next_days/', views.fiveDays, name='fiveDays'),
]

a22207718/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('novaapp/', include('novaapp.urls')),
    path('bandas/', include('bandas.urls')),
    path('artigos/', include('artigos.urls')),
    path('curso/', include('curso.urls')),
    path('festivais/', include('festivais.urls')),
    path('authentication/', include('authentication.urls')),
    path('Meteo/', include('Meteo.urls')),
    path('', include('Portfolio.urls')),
]

curso/urls.py
from django.urls import path
from . import views


app_name = 'curso'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('', views.intro_view, name='intro_view'),
    path('curso/<int:curso_id>/', views.todasDisciplinas_view, name='disciplinas'),
    path('projetos/', views.projetos_view, name='projetos_view'),
    path('disciplina/<int:disciplina_id>/', views.disciplina_details, name='disciplina_details'),
    path('project/<int:project_id>/', views.project_details, name='project_details'),

]

curso/models.py
from django.db import models

class Curso(models.Model):
    apresentacao = models.CharField(max_length=50)
    objectivos = models.CharField(max_length=50)
    competencias = models.CharField(max_length=50)

    def _str_(self):
        return f"Apresentação: {self.apresentacao} objetivos: {self.objectivos} competencias: {self.competencias}"


class area_Cientifica(models.Model):
    area = models.CharField(max_length=50)

    def _str_(self):
        return f"Area: {self.area} "

class disciplina(models.Model):
    nome= models.CharField(max_length=50)
    linguagemProgramacao = models.CharField(max_length=50, default='Python')
    ano= models.IntegerField()
    semestre = models.IntegerField()
    ects = models.IntegerField()
    curricular_IUnit_Readable_Code = models.CharField(max_length=50)

    def _str_(self):
        return f"Disciplina: {self.nome}, ano: {self.ano}, semestre: {self.semestre}, ects: {self.ects}, Codigo: {self.curricular_IUnit_Readable_Code} "

class projeto(models.Model):
    projeto = models.CharField(max_length=50)
    disciplina = models.ForeignKey(disciplina, on_delete=models.CASCADE, related_name='projetos')
    ano = models.IntegerField()
    semestre = models.IntegerField()
    descricao = models.CharField(max_length=50)
    conceitos_aplicados = models.CharField(max_length=50)
    link_video = models.CharField(max_length=50)
    link_gitHub = models.CharField(max_length=50)

    def _str_(self):
        return f"O projeto '{self.projeto}' desenvolvido no {self.semestre}º semestre do {self.ano}º ano\nDescrição: {self.descricao}\nConceitos: {self.conceitos_aplicados}\nLinks: {self.link_video}, {self.link_gitHub} "


class Docente(models.Model):
    nome = models.CharField(max_length=50)
    disciplinas = models.ManyToManyField(disciplina)

    def _str_(self):
        return f"{self.nome} leciona: {self.disciplinas}"

curso/views.py
from django.shortcuts import render, redirect
from .models import Curso,disciplina,projeto



def login_view(request):
    return redirect('authentication/login')

def intro_view(request):
    cursos = Curso.objects.all()
    context = {
        'cursos': cursos
    }
    return render(request, 'curso/intro.html', context)


def todasDisciplinas_view(request, curso_id):
    curso = Curso.objects.get(id=curso_id)
    disciplinas = disciplina.objects.all()
    return render(request, 'curso/todasDisciplinas.html', {'curso': curso, 'disciplinas': disciplinas})


def disciplina_details(request, disciplina_id):
    disciplina1 = disciplina.objects.get(id=disciplina_id)
    projetos = disciplina1.projetos.all()
    return render(request, 'curso/disciplina_details.html', {'disciplina': disciplina1, 'projetos': projetos})

def project_details(request, project_id):
    project = projeto.objects.get(id=project_id)
    return render(request, 'curso/project_details.html', {'project': project})

def projetos_view(request):
    projetos = projeto.objects.all().order_by('ano')
    return render(request, 'curso/projetos.html', {'projetos': projetos})

curso/templates/curso/disciplina.html
{% extends 'curso/layout.html' %}

{% block content %}
    <ul>
    {% for curso in cursos %}
        <li>
            <strong>Disciplina:</strong> {{ disciplina.nome }} <br>

        </li>

    {% endfor %}
    </ul>
{% endblock %}

curso/templates/curso/disciplina_details.html
{% extends 'curso/layout.html' %}

{% block content %}
    <h1>{{ disciplina.nome }}</h1>
    <p><strong>Ano:</strong> {{ disciplina.ano }}</p>
    <p><strong>Semestre:</strong> {{ disciplina.semestre }}</p>
    <p><strong>ECTS:</strong> {{ disciplina.ects }}</p>
    <p><strong>Código Curricular:</strong> {{ disciplina.curricular_IUnit_Readable_Code }}</p>
    <p><strong>Linguagem de Programação:</strong> {{ disciplina.linguagemProgramacao }}</p>
    <hr>
    <h2>Projetos</h2>
    {% for projeto in projetos %}
        <a href="{% url 'curso:project_details' projeto.id %}"><h3>{{ projeto.projeto }}</h3></a>
    {% endfor %}

{% endblock %}

curso/templates/curso/intro.html
{% extends 'curso/layout.html' %}

{% block content %}
    <ul>
    {% for curso in cursos %}
    <li>
        <a href="{% url 'curso:disciplinas' curso.id %}">
            <div style="margin-right: 50px;">
                
                    <h2><strong>{{ curso.apresentacao }}</strong></h2>
                
            </div>
        </a>  
        <div style="margin-right: 50px;">
            <strong>Objetivos:</strong><br>
            {{ curso.objectivos }}
        </div>
        <div>
            <strong>Competências:</strong><br>
            {{ curso.competencias }}
        </div>
         
    </li> 
    <hr>
    {% endfor %}
    </ul>
{% endblock %}

curso/templates/curso/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mundo Acadêmico</title>
    <style>

        body {
            background: #f5f5f5; /* Altera a cor de fundo do body */
            color: #333; /* Altera a cor do texto */
            font-family: 'Roboto', sans-serif;
            margin: 0;
            padding: 0;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }

        a {
            color: #333; /* Altera a cor dos links */
            text-decoration: none;
        }

        a:hover {
            color: #666; /* Altera a cor dos links ao passar o mouse */
        }

        header {
            padding: 20px 0; /* Adiciona espaçamento interno ao header */
            text-align: center;
            background-color: #fff; /* Adiciona um fundo branco ao header */
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Adiciona sombreado suave ao header */
            border-bottom: 1px solid #ddd; /* Adiciona uma borda inferior */
        }

        h1 {
            font-size: 36px;
            margin: 0;
        }

        button {
            background-color: #666; /* Altera a cor de fundo do botão */
            color: #fff; /* Altera a cor do texto do botão */
            border: none;
            padding: 10px 20px;
            cursor: pointer;
            border-radius: 4px; /* Adiciona bordas arredondadas ao botão */
            transition: background-color 0.3s ease; /* Adiciona transição suave */
        }

        button:hover {
            background-color: #555; /* Altera a cor de fundo do botão ao passar o mouse */
        }

        main {
            flex: 1;
            margin: 20px;
            background-color: #fff; /* Adiciona um fundo branco ao conteúdo principal */
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Adiciona sombreado suave */
            border-radius: 4px; /* Adiciona bordas arredondadas */
            padding: 20px;
        }

        footer {
            background-color: #fff; /* Adiciona um fundo branco ao footer */
            padding: 20px 0;
            text-align: center;
            border-top: 1px solid #ddd; /* Adiciona uma borda superior */
        }

    </style>
</head>
<body>

<header>
    <h1>Mundo Acadêmico</h1>
    <a href="{% url 'curso:intro_view' %}"><button>Home</button></a>
</header>

<main>
    {% block content %}
    {% endblock %}
</main>

<footer>
    <p>Mundo Acadêmico By Bruno Ramos</p>
</footer>

</body>
</html>

curso/templates/curso/project_details.html
{% extends 'curso/layout.html' %}

{% block content %}
    <h1>Project Details</h1>
    <p><strong>Name:</strong> {{ project.projeto }}</p>
    <p><strong>Ano:</strong> {{ project.ano }}</p>
    <p><strong>Semestre:</strong> {{ project.semestre }}</p>
    <p><strong>Descrição:</strong> {{ project.descricao }}</p>
    <p><strong>Conceitos Aplicados:</strong> {{ project.conceitos_aplicados }}</p>
    <p><a href="{{ project.link_video }}"><strong>Link youtube: </strong>{{ project.link_video }}</a></p>
    <p><a href="{{ project.link_gitHub }}"><strong>Link gitHub: </strong>{{ project.link_gitHub }}</a></p>
{% endblock %}

curso/templates/curso/projetos.html
{% extends 'curso/layout.html' %}

{% block content %}
    <ul>
    {% for project in projetos %}
        <li>
            <a href="{% url 'curso:project_details' project.id %}">
                <strong>Name:</strong> {{ project.projeto }} <br>
            </a>
        </li>
        <br>
    {% endfor %}
    </ul>
{% endblock %}

curso/templates/curso/todasDisciplinas.html
{% extends 'curso/layout.html' %}

{% block content %}
    <h2>{{ curso.apresentacao }}</h2>

    <ul>
        {% for disciplina in disciplinas %}
            <li>
                <a href="{% url 'curso:disciplina_details' disciplina.id %}">
                    {{ disciplina.nome }}<br>
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}