Meteo/urls.py
from django.urls import path
from . import views

app_name = 'Meteo'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('registo/', views.registo_view, name='registo'),
    path('', views.home, name='home'),
    path('next_days/', views.fiveDays, name='fiveDays'),
]

Portfolio/urls.py
from django.urls import path
from . import views

app_name = 'Portfolio'

urlpatterns = [
    path('', views.home, name='home'),
    path('meByme/', views.meByme, name='meByme'),
    path('WebWizardry/', views.WebWizardry, name='WebWizardry'),
    path('automation/', views.automation, name='automation'),
    path('projects/', views.projects, name='projects'),
]

a22207718/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('novaapp/', include('novaapp.urls')),
    path('bandas/', include('bandas.urls')),
    path('artigos/', include('artigos.urls')),
    path('curso/', include('curso.urls')),
    path('festivais/', include('festivais.urls')),
    path('authentication/', include('authentication.urls')),
    path('Meteo/', include('Meteo.urls')),
    path('', include('Portfolio.urls')),
]

artigos/urls.py
from django.urls import path
from . import views

app_name='artigos'

urlpatterns = [
    path('', views.lista_artigos, name='lista_artigos'),
    path('novo/', views.novo_artigo, name='novo_artigo'),
]

bandas/urls.py
from django.urls import path
from . import views

app_name = 'bandas'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('registo/', views.registo_view, name='registo'),
    path('', views.pagina_inicial, name='pagina_inicial'),
    path('albuminfo/<int:album_id>/', views.albuminfo_view, name='albuminfo'),
    path('musicainfo/<int:musica_id>/', views.musicainfo_view, name='musicainfo'),
    path('bandalbuns/<int:banda_id>/', views.bandalbuns_view, name='bandalbuns'),
    path('musica-favorita/', views.musica_favorita, name='musica_favorita'),
    path('bandas-json/', views.bandas_json_view, name='bandas_json'),
]

curso/urls.py
from django.urls import path
from . import views


app_name = 'curso'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('', views.intro_view, name='intro_view'),
    path('curso/<int:curso_id>/', views.todasDisciplinas_view, name='disciplinas'),
    path('projetos/', views.projetos_view, name='projetos_view'),
    path('disciplina/<int:disciplina_id>/', views.disciplina_details, name='disciplina_details'),
    path('project/<int:project_id>/', views.project_details, name='project_details'),

]

festivais/urls.py
from django.urls import path
from . import views


app_name= "festivais"
urlpatterns = [
    path('', views.lista_festivais, name='lista_festivais'),
    path('festivais/<int:festival_id>/', views.detalhes_festival, name='detalhes_festival'),
]

Portfolio/models.py
from django.db import models

# Create your models here.

Portfolio/views.py
from django.shortcuts import render, redirect


def meByme(request):
    return render(request, 'Portfolio/meByme.html')

def home(request):
    return render(request, 'Portfolio/home.html')

def WebWizardry(request):
    return render(request, 'Portfolio/WebWizardry.html')

def automation(request):
    return render(request, 'Portfolio/automation.html')

def projects(request):
    return render(request, 'Portfolio/projects.html')

Portfolio/templates/Portfolio/WebWizardry.html
{% extends 'Portfolio/layout.html' %}
{% load static %}
{% block content %}

<div id="webWizardry" class="content parallax">
    <h2>WebWizardry</h2>
    <p>Este website foi desenvolvido utilizando uma variedade de tecnologias. Abaixo estão listadas algumas delas:</p>
    <ul>
        <li>HTML5 e CSS3 para estrutura e estilo</li>
        <li>JavaScript para funcionalidades dinâmicas</li>
        <li>Font Awesome para ícones</li>
        <li>API de Meteorologia para informações de tempo</li>
    </ul>
    <h1>Apresentação das minhas aplicações</h1>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/4AvrT_3GnPc" frameborder="0" allowfullscreen></iframe>
</div>

{% endblock content %}

Portfolio/templates/Portfolio/automation.html
{% extends 'Portfolio/layout.html' %}
{% load static %}

{% block content %}
<div class="content">
    <h2>Automation</h2>
    <p>Aqui estão algumas automações que desenvolvi para facilitar diversas tarefas.</p>
</div>
{% endblock %}

Portfolio/templates/Portfolio/home.html
{% extends 'Portfolio/layout.html' %}
{% load static %}
{% block content %}
<div id="home" class="hero">
    <h1>Bem-vindo ao meu Portfólio!</h1>
    <p>Explore e conheça mais sobre mim e os meus projetos.</p>
</div>
{% endblock content %}

Portfolio/templates/Portfolio/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bruno Ramos</title>
    <link rel="stylesheet" href="{% static 'Portfolio/estilo.css' %}">
    <link rel="stylesheet" href="{% static 'Portfolio/estilo.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="icon" href="{% static 'Portfolio/BR.png' %}" type="image/x-png">
</head>
<body>

<nav>
    <div>
        <a href="{% url 'Portfolio:home' %}">Home</a>
        <a href="{% url 'Portfolio:meByme' %}">MeByMe</a>
        <a href="{% url 'Portfolio:WebWizardry' %}">WebWizardry</a>
        <a href="{% url 'Portfolio:automation' %}">Automation</a>
        <a href="{% url 'Portfolio:projects' %}">Projects</a>
    </div>

    <div>
        <a href="{% url 'Meteo:home' %}"><i class="fas fa-cloud-sun"></i> Weather</a>
        <a href="{% url 'authentication:login_view' %}" id="loginButton"><i class="fas fa-sign-in-alt"></i> Login</a>
        <a href="#" id="darkModeToggle"><i class="fas fa-moon"></i></a>
    </div>
</nav>

{% block content %}
{% endblock %}


<div id="clock"></div>

<script>
    const toggleButton = document.getElementById('darkModeToggle');
    toggleButton.addEventListener('click', () => {
        document.body.classList.toggle('dark-mode');
    });

    function updateClock() {
        const now = new Date();
        const hours = now.getHours().toString().padStart(2, '0');
        const minutes = now.getMinutes().toString().padStart(2, '0');
        const seconds = now.getSeconds().toString().padStart(2, '0');
        document.getElementById('clock').textContent = `${hours}:${minutes}:${seconds}`;
    }
    setInterval(updateClock, 1000);
    updateClock();
</script>
<footer>
    <p>&copy; 2024 Bruno Ramos. Todos os direitos reservados.</p>
</footer>
</body>
</html>

Portfolio/templates/Portfolio/meByme.html
{% extends 'Portfolio/layout.html' %}
{% load static %}
{% block content %}
<div class="content">
    <h2>MeByMe</h2>
    <div class="flex-container">
        <a href="{% static 'Portfolio/Bruno Ramos - CV (programmer).pdf' %}" type="application/pdf" target="_blank">
        <img src="{%static 'Portfolio/brunoFormal_bottomFade_NoBG.png'%}" width=500px >
        </a>
        <div class="flex-item">
            <h3>Sobre Mim</h3>
            <p>Sou Bruno, estudante de Ciência da Computação e Engenharia. Tenho paixão pelo mundo digital, criação de jogos, aplicações móveis e desktop, e cartoons. Desenho digitalmente como hobby e estou a aprofundar os meus conhecimentos em Java e outras tecnologias de programação.</p>
        </div>
        <div class="flex-item">
            <h3>Competências</h3>
            <ul>
                <li>Programação em Java</li>
                <li>Desenho Digital</li>
                <li>Desenvolvimento Web</li>
                <li>Criação de Jogos</li>
            </ul>
        </div>
        <div class="flex-item">
            <h3>Experiência</h3>
            <ul>
                <li>Projetos de Programação na Universidade</li>
                <li>Desenvolvimento de Websites Pessoais</li>
                <li>Participação em Hackathons</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

Portfolio/templates/Portfolio/projects.html
{% extends 'Portfolio/layout.html' %}
{% load static %}
{% block content %}
<div class="projects-container">
    <h1>Projects</h1>
    <div class="cards-container">

        <div class="card">
            <a href="{% url 'bandas:pagina_inicial' %}" class="card-link">
                <img src="https://cdn-icons-png.flaticon.com/512/1746/1746777.png" alt="Bandas" class="card-image">
                <div class="card-content">
                    <h2>App Bandas</h2>
                </div>
            </a>
        </div>

        <div class="card">
            <a href="{% url 'curso:intro_view' %}" class="card-link">
                <img src="https://th.bing.com/th/id/R.2242a2202fb8e8717b1c46cd46d22dda?rik=NJ8JGKgTc91Lgg&pid=ImgRaw&r=0" alt="Curso" class="card-image">
                <div class="card-content">
                    <h2>App Curso</h2>
                </div>
            </a>
        </div>

        <div class="card">
            <a href="{% url 'festivais:lista_festivais' %}" class="card-link">
                <img src="https://cdn-icons-png.flaticon.com/512/9457/9457853.png" alt="festivais" class="card-image">
                <div class="card-content">
                    <h2>App Festivais</h2>
                </div>
            </a>
        </div>

        <div class="card">
            <a href="{% url 'artigos:lista_artigos' %}" class="card-link">
                <img src="https://cdn-icons-png.flaticon.com/512/443/443404.png" alt="artigos" class="card-image">
                <div class="card-content">
                    <h2>App Artigos</h2>
                </div>
            </a>
        </div>

        <div class="card">
            <a href="{% url 'Meteo:home' %}" class="card-link">
                <img src="https://cdn.icon-icons.com/icons2/1548/PNG/512/cloud_107348.png" alt="meteo" class="card-image">
                <div class="card-content">
                    <h2>App Meteo</h2>
                </div>
            </a>
        </div>


    </div>
</div>
{% endblock %}