Meteo/urls.py
from django.urls import path
from . import views

app_name = 'Meteo'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('registo/', views.registo_view, name='registo'),
    path('', views.home, name='home'),
    path('next_days/', views.fiveDays, name='fiveDays'),
]

a22207718/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('novaapp/', include('novaapp.urls')),
    path('bandas/', include('bandas.urls')),
    path('artigos/', include('artigos.urls')),
    path('curso/', include('curso.urls')),
    path('festivais/', include('festivais.urls')),
    path('authentication/', include('authentication.urls')),
    path('Meteo/', include('Meteo.urls')),
    path('', include('Portfolio.urls')),
]

authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('signin/', views.signin, name='signin'),
    path('recover_password/', views.recover_password, name='recover_password'),
]

bandas/urls.py
from django.urls import path
from . import views

app_name = 'bandas'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('registo/', views.registo_view, name='registo'),
    path('', views.pagina_inicial, name='pagina_inicial'),
    path('albuminfo/<int:album_id>/', views.albuminfo_view, name='albuminfo'),
    path('musicainfo/<int:musica_id>/', views.musicainfo_view, name='musicainfo'),
    path('bandalbuns/<int:banda_id>/', views.bandalbuns_view, name='bandalbuns'),
    path('musica-favorita/', views.musica_favorita, name='musica_favorita'),
    path('bandas-json/', views.bandas_json_view, name='bandas_json'),
]

bandas/models.py
from django.db import models

class Musica(models.Model):
    titulo = models.CharField(max_length=100)
    album = models.ForeignKey('Album', on_delete=models.CASCADE, related_name='musicas')
    duracao = models.DurationField()
    link_spotify = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.titulo

class Banda(models.Model):
    nome = models.CharField(max_length=100)
    genero = models.CharField(max_length=100)
    foto = models.ImageField(upload_to='bandas/', null=True, blank=True)

    def __str__(self):
        return self.nome

class Album(models.Model):
    titulo = models.CharField(max_length=100)
    banda = models.ForeignKey('Banda', on_delete=models.CASCADE, related_name='albuns')
    lancamento = models.DateField()
    capa = models.ImageField(upload_to='capas/', null=True, blank=True)

    def __str__(self):
        return self.titulo

bandas/views.py
from bandas.models import Album, Banda, Musica
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse

def login_view(request):
    return redirect('authentication/login')

def registo_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('pagina_inicial')
    else:
        form = UserCreationForm()
    return render(request, 'bandas/registo.html', {'form': form})


def albuminfo_view(request, album_id):
    album = Album.objects.get(id=album_id)
    context = {
        'album': album,
        'musicas': album.musicas.all(),
    }
    return render(request, "bandas/albumInfo.html", context)

def musica_favorita(request):
    return render(request, 'bandas/musica_favorita.html')

def pagina_inicial(request):
    bandas = Banda.objects.all().order_by('-nome')
    context = {'bandas': bandas}
    return render(request, 'bandas/paginaInicial.html', context)

def bandas_json_view(request):
    bandas = Banda.objects.all()
    bandas_nomes = [banda.nome for banda in bandas]
    return JsonResponse({'bandas': bandas_nomes})

def musicainfo_view(request, musica_id):
    musica = Musica.objects.get(id=musica_id)
    context = {'musica': musica}
    return render(request, 'bandas/musicaInfo.html', context)


def bandalbuns_view(request, banda_id):
    banda = Banda.objects.get(id=banda_id)
    albuns = banda.albuns.all()
    numMusics = 0
    for album in albuns:
        numMusics += album.musicas.count()
    context = {
        'banda': banda,
        'albuns': albuns,
        'numAlbuns': len(albuns),
        'numMusicas': numMusics,
    }
    return render(request, "bandas/bandaAlbuns.html", context)

bandas/templates/bandas/albumInfo.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <li>
        <a href="javascript:window.history.back();" style="display: block; text-align: center;">
            <h2>voltar</h2>
        </a>
    </li>
    <h1>Detalhes do Álbum "{{ album.titulo }}"</h1>
    <p>Banda: {{ album.banda.nome }}</p>
    <p>Data de Lançamento: {{ album.lancamento }}</p>

    <ul>
        <img src="{{ album.capa.url }}" alt="Capa do Álbum" style="width: 400px; height: auto;">
    </ul>

    <h2>Músicas do Álbum:</h2>
    <ul>
    {% for musica in musicas %}
        <li><a href="{% url 'bandas:musicainfo' musica.id %}">{{ musica.titulo }}</a></li>

    {% endfor %}
    </ul>


{% endblock %}

bandas/templates/bandas/bandaAlbuns.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <li>
        <a href="javascript:window.history.back();" style="display: block; text-align: center;">
            <h2>voltar</h2>
        </a>
    </li>
    <h1>Álbuns da Banda {{ banda.nome }}</h1>
    <h3>A banda {{ banda.nome }} possui {{numMusicas}} músicas e {{numAlbuns}} albuns.</h3>
    <ul class="banda-albuns">
        {% for album in albuns %}
                <br>
            <div>
                <h2>{{ album.titulo }}</h2>
                <li>
                    <a href="{% url 'bandas:albuminfo' album.id %}">
                        <img src="{{ album.capa.url }}" alt="Capa do Álbum" style="width: 300px; height: auto;">
                    </a>
                </li>

            </div>

        {% endfor %}
    </ul>
{% endblock %}

bandas/templates/bandas/layout.html
{% load static %}
<html>
  <head>
        <title>Music Culture</title>
        <link rel="stylesheet" href="{% static 'bandas/estilo.css' %}">
  </head>
  <body>
    <div class="container">
    <header>
      <div class="div_title"><h1>Music Culture</h1></div>
      <div class="div_buttons">
        <a class= "home-button" href="{% url 'bandas:pagina_inicial' %}">Home</a>
        <a class= "login-button" href="{% url 'authentication:login_view' %}">Login</a>
      </div>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer>
      <p>Music Culture By Bruno Ramos</p>
    </footer>
  </div>
  </body>
</html>

bandas/templates/bandas/login.html
{% extends 'bandas/layout.html' %}

{% block content %}
<h1>Login</h1>
    <form method="post" action="{% url 'bandas:login' %}">
        {% csrf_token %}
        <label for="username">Nome de Utilizador:</label>
        <input type="text" id="username" name="username" required>
        <br>
        <br>
        <label for="password">Senha:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <br>
        <button type="submit">Entrar</button>
    </form>


{% endblock %}

bandas/templates/bandas/musicaInfo.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <li>
        <a href="javascript:window.history.back();" style="display: block; text-align: center;">
            <h2>voltar</h2>
        </a>
    </li>
    <h1>Detalhes da Música "{{ musica.titulo }}"</h1>
    <p>Duração: {{ musica.duracao }}</p>
    <p>Link do YouTube: <a href="{{ musica.link_spotify }}">{{ musica.link_spotify }}</a></p>
    <h2>Vídeo do YouTube</h2>
    <embed width="560" height="315" src="{{ musica.link_spotify }}" frameborder="0" allowfullscreen></embed>

{% endblock %}

bandas/templates/bandas/musica_favorita.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <li>
        <a href="javascript:window.history.back();" style="display: block; text-align: center;">
            <h2>voltar</h2>
        </a>
    </li>
    <h1>Minha Música Favorita</h1>
    <div class="favorite-music-container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/GG7fLOmlhYg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
{% endblock %}

bandas/templates/bandas/paginaInicial.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h1>Lista de Bandas</h1>
    <ul class="horizontal-cards">
        {% for banda in bandas %}
            <li class="li_bandas">
                <a href="{% url 'bandas:bandalbuns' banda.id %}">
                    <img class="banda_foto" src="{{ banda.foto.url }}" alt="Foto da Banda">
                    <div style="position: absolute; top: 0; left: 0; background-color: rgba(7, 7, 7, 0.7); padding: 10px;">
                        <h3>{{ banda.nome }}</h3>
                    </div>
                </a>
            </li>
            <br>
        {% endfor %}
    </ul>
    <br>
    <div class="favBottun"><a href="{% url 'bandas:musica_favorita' %}" class="favorite-music-button">Minha Música Favorita</a></div>
    <br>
    <button id="loadBandasButton">Carregar Nomes das Bandas</button>
    <div id="bandasJson"></div>

    <script>
        document.getElementById('loadBandasButton').addEventListener('click', function() {
            fetch("{% url 'bandas:bandas_json' %}")
                .then(response => response.json())
                .then(data => {
                    document.getElementById('bandasJson').innerText = JSON.stringify(data.bandas, null, 2);
                })
                .catch(error => console.error('Error:', error));
        });
    </script>
{% endblock %}

bandas/templates/bandas/registo.html

{% extends 'bandas/layout.html' %}

{% block content %}
<form method="post" action="{% url 'bandas:registo' %}">
  {% csrf_token %}
  <label for="username">Nome de Utilizador:</label>
  <input type="text" id="username" name="username" required>
  <label for="email">Email:</label>
  <input type="email" id="email" name="email" required>
  <label for="password">Senha:</label>
  <input type="password" id="password" name="password" required>
  <button type="submit">Registrar</button>
</form>

{% endblock %}